/*
 * Aquí se muestra la información al usuario y se presentan opciones para que este interactúe con el árbol binario.
 */
package proyecto2;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author Andres B
 */
public class Pantalla extends javax.swing.JFrame {

    Arbol Arbol=new Arbol();
    int Numero;
    
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextFieldIngresarNumero = new javax.swing.JTextField();
        LabelConfirmador = new javax.swing.JLabel();
        BotonIngresarNumero = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        BotonMostrarDatos = new javax.swing.JButton();
        BotonReiniciarArbol = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto 2");

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Árboles binarios");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese un número en el árbol binario:");

        TextFieldIngresarNumero.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
                    e.consume();  // if it's not a number, ignore the event
                }
            }
        });
        TextFieldIngresarNumero.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        TextFieldIngresarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIngresarNumeroActionPerformed(evt);
            }
        });

        LabelConfirmador.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        LabelConfirmador.setForeground(new java.awt.Color(255, 255, 255));
        LabelConfirmador.setText("Aquí se avisará si el número ha sido ingresado o no.");

        BotonIngresarNumero.setBackground(new java.awt.Color(255, 255, 255));
        BotonIngresarNumero.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        BotonIngresarNumero.setText("Ingresar número");
        BotonIngresarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarNumeroActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lista de datos del árbol:");

        TextArea.setColumns(20);
        TextArea.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        TextArea.setRows(5);
        TextArea.setText("Presione \"Mostrar datos\" para mostrar:\nInOrder\nPreOrder\nPostOrder\nNodos\nHojas\nAltura\nMayor valor\nMenor valor");
        jScrollPane3.setViewportView(TextArea);
        TextArea.setEditable(false);

        BotonMostrarDatos.setBackground(new java.awt.Color(255, 255, 255));
        BotonMostrarDatos.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        BotonMostrarDatos.setText("Mostrar datos");
        BotonMostrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarDatosActionPerformed(evt);
            }
        });

        BotonReiniciarArbol.setBackground(new java.awt.Color(255, 255, 255));
        BotonReiniciarArbol.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        BotonReiniciarArbol.setText("Reiniciar árbol");
        BotonReiniciarArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReiniciarArbolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BotonIngresarNumero)
                        .addGap(234, 234, 234))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(TextFieldIngresarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(LabelConfirmador))
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BotonMostrarDatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonReiniciarArbol))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextFieldIngresarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LabelConfirmador)
                .addGap(34, 34, 34)
                .addComponent(BotonIngresarNumero)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonMostrarDatos)
                    .addComponent(BotonReiniciarArbol))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldIngresarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIngresarNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIngresarNumeroActionPerformed

    private void BotonIngresarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarNumeroActionPerformed
        if(!TextFieldIngresarNumero.getText().isEmpty()){
            Numero=Integer.parseInt(TextFieldIngresarNumero.getText());
            if(Arbol.existe(Numero)){
                LabelConfirmador.setText("Error: El número "+Numero+" ya está en el árbol.");
            }
            else{
                Arbol.insertar(Numero);
                LabelConfirmador.setText("El número "+Numero+ " ha sido ingresado");
            }
        }
        else{
            LabelConfirmador.setText("Error: No se ha ingresado un número.");
        }
        TextFieldIngresarNumero.setText("");
        
    }//GEN-LAST:event_BotonIngresarNumeroActionPerformed

    private void BotonMostrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarDatosActionPerformed
        if(Arbol.EstaVacio()){
            TextArea.setText("El árbol está vacío.");
        }
        else{
            LabelConfirmador.setText("Aquí se avisará si el número ha sido ingresado o no.");
            
            TextArea.setText("Datos del arbol creado: \nInOrder: "+Arbol.inorden()+"\nPreOrder: "+Arbol.preorden()+"\nPostOrder: "+Arbol.postorden()+
                             "\nNúmero de nodos: "+Arbol.CuentaNodos(Arbol.getRaiz())+"\nNúmero de hojas: "+Arbol.CuentaHojas(Arbol, Arbol.getRaiz())+
                             "\nAltura: "+Arbol.Altura(Arbol.getRaiz())+"\nMayor valor: "+Arbol.BuscarMayor()+"\nMenor valor: "+Arbol.BuscarMenor());
        
            //Arbol.getRaiz().Borrar(Arbol.BuscarMenor());
            Arbol.VaciarStrings();
        } 
    }//GEN-LAST:event_BotonMostrarDatosActionPerformed
    
    //Se ha agregado esta función para que el sistema se reinicie y se pueda utilizar múltiples veces desde cero.
    private void BotonReiniciarArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReiniciarArbolActionPerformed
        TextArea.setText("El árbol ha sido reiniciado.");
        Arbol.EliminarTodo(); 
    }//GEN-LAST:event_BotonReiniciarArbolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIngresarNumero;
    private javax.swing.JButton BotonMostrarDatos;
    private javax.swing.JButton BotonReiniciarArbol;
    private javax.swing.JLabel LabelConfirmador;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JTextField TextFieldIngresarNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}

/*
    Enlaces: 

    Árboles binarios: https://www.youtube.com/watch?v=MmA9ZJJhiYM

    https://parzibyte.me/blog/2020/05/08/arbol-binario-java/
*/
